<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lekiwi">

  <!-- Include robot properties -->
  <xacro:include filename="$(find lekiwi_description)/urdf/base_properties.xacro"/>

  <!-- Define custom materials for base and wheels using color properties -->
  <material name="light_grey">
    <color rgba="${light_grey_rgba}"/>
  </material>
  <material name="charcoal">
    <color rgba="${charcoal_rgba}"/>
  </material>

  <!-- LINKS -->

  <!-- Base footprint link (empty) -->
  <link name="base_footprint"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${base_offset_rz}"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/lekiwi_base.stl"/>
      </geometry>
      <material name="light_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${base_offset_rz}"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/lekiwi_base.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.02"/>
    </inertial>
  </link>

  <!-- LD06 laser link -->
  <link name="laser_link">
    <visual>
      <origin xyz="0 0 0" rpy="${laser_offset_rx} 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/ld06_lidar.stl"/>
      </geometry>
      <material name="charcoal"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${laser_offset_rx} 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/ld06_lidar.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- Laser frame -->
  <link name="laser_frame"/>

  <!-- Camera link -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/hd_webcam.stl"/>
      </geometry>
      <material name="charcoal"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/hd_webcam.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
    </inertial>
  </link>

  <!-- Camera frame-->
  <link name="camera_frame"/>

  <!-- Left wheel link -->
  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${wheel_offset_rx} 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/omni_wheel.stl"/>
      </geometry>
      <material name="charcoal"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${wheel_offset_rx} 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/omni_wheel.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Back wheel link -->
  <link name="back_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${wheel_offset_rx} 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/omni_wheel.stl"/>
      </geometry>
      <material name="charcoal"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${wheel_offset_rx} 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/omni_wheel.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Right wheel link -->
  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${wheel_offset_rx} 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/omni_wheel.stl"/>
      </geometry>
      <material name="charcoal"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${wheel_offset_rx} 0 0"/>
      <geometry>
        <mesh filename="package://lekiwi_description/meshes/omni_wheel.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- JOINTS -->

  <!-- base_footprint fixed joint -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_footprint_offset_z}" rpy="0 0 0"/>
  </joint>

  <!-- laser fixed joint -->
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="${laser_base_offset_x} 0 ${laser_base_offset_z}" rpy="0 0 0"/>
  </joint>

  <!-- laser_frame fixed joint -->
  <joint name="laser_frame_joint" type="fixed">
    <parent link="laser_link"/>
    <child link="laser_frame"/>
    <origin xyz="0 0 ${laser_frame_offset_z}" rpy="0 0 0"/>
  </joint>

  <!-- camera fixed joint -->
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${camera_base_offset_x} 0 ${camera_base_offset_z}" rpy="0 ${camera_offset_ry} 0"/>
  </joint>

  <!-- camera_frame fixed joint -->
  <joint name="camera_frame_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- left wheel joint: 60 degrees anti-clockwise from +X at radius wheel_base_radius -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="${wheel_base_radius * cos(offset)} ${wheel_base_radius * sin(offset)} ${wheel_base_offset_z}" rpy="0 ${pi/2} ${offset}"/>
    <axis xyz="0 0 1"/>
    <limit effort="${max_torque_nm}" velocity="${max_velocity_rads}"/>
  </joint>

  <!-- back wheel joint: 180 degrees anti-clockwise from +X at radius base_radius -->
  <joint name="back_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_wheel_link"/>
    <origin xyz="${wheel_base_radius * cos(offset + theta)} ${wheel_base_radius * sin(offset + theta)} ${wheel_base_offset_z}" rpy="0 ${pi/2} ${offset + theta}"/>
    <axis xyz="0 0 1"/>
    <limit effort="${max_torque_nm}" velocity="${max_velocity_rads}"/>
  </joint>

  <!-- right wheel joint: 300 degrees (or -60 degrees) anti-clockwise from +X at radius base_radius -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="${wheel_base_radius * cos(offset - theta)} ${wheel_base_radius * sin(offset - theta)} ${wheel_base_offset_z}" rpy="0 ${pi/2} ${offset - theta}"/>
    <axis xyz="0 0 1"/>
    <limit effort="${max_torque_nm}" velocity="${max_velocity_rads}"/>
  </joint>

  <!-- ROS 2 CONTROL -->
  <!-- System interface -->
  <ros2_control name="lekiwi_base" type="system">
    <hardware>
      <plugin>sts_hardware_interface/STSHardwareInterface</plugin>
      <!-- Serial communication parameters -->
      <param name="serial_port">${serial_port}</param>
      <param name="baud_rate">${baud_rate}</param>
      <param name="use_sync_write">true</param>
      <param name="enable_multi_turn">true</param>
      <param name="enable_mock_mode">false</param>
    </hardware>
    <!-- Left wheel joint (Motor ID 7) -->
    <joint name="left_wheel_joint">
      <param name="motor_id">${left_motor_id}</param>
      <param name="operating_mode">${operating_mode}</param>
      <command_interface name="velocity"/>
      <command_interface name="acceleration"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
      <state_interface name="voltage"/>
      <state_interface name="temperature"/>
      <state_interface name="current"/>
      <state_interface name="is_moving"/>
    </joint>
    <!-- Back wheel joint (Motor ID 8) -->
    <joint name="back_wheel_joint">
      <param name="motor_id">${back_motor_id}</param>
      <param name="operating_mode">${operating_mode}</param>
      <command_interface name="velocity"/>
      <command_interface name="acceleration"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
      <state_interface name="voltage"/>
      <state_interface name="temperature"/>
      <state_interface name="current"/>
      <state_interface name="is_moving"/>
    </joint>
    <!-- Right wheel joint (Motor ID 9) -->
    <joint name="right_wheel_joint">
      <param name="motor_id">${right_motor_id}</param>
      <param name="operating_mode">${operating_mode}</param>
      <command_interface name="velocity"/>
      <command_interface name="acceleration"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
      <state_interface name="voltage"/>
      <state_interface name="temperature"/>
      <state_interface name="current"/>
      <state_interface name="is_moving"/>
    </joint>
  </ros2_control>

</robot>
