<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- LeKiwi physical dimensions -->
  <xacro:property name="wheel_radius" value="0.051"/>
  <xacro:property name="wheel_thickness" value="0.0394"/>
  <xacro:property name="base_radius" value="0.108"/>
  <xacro:property name="wheel_base_offset" value="0.1322"/>

  <!-- Wheel geometry for omnidirectional control -->
  <xacro:property name="offset" value="${pi/3}"/>  <!-- 60° -->
  <xacro:property name="theta" value="${2*pi/3}"/>  <!-- 120° between wheels -->

  <!-- Motor control parameters -->
  <xacro:property name="operating_mode" value="1"/>  <!-- Velocity mode -->
  <xacro:property name="serial_port" value="/dev/ttySERVO"/>
  <xacro:property name="baud_rate" value="1000000"/>

  <!-- Maximum allowable speed for each motor -->
  <xacro:property name="max_velocity_steps" value="2720"/> <!-- steps/second (80% of 3400 hardware max) -->
  <xacro:property name="max_velocity_rads" value="${max_velocity_steps*2*pi/4096}"/> <!-- rad/s -->

  <!-- Maximum allowable acceleration for each motor -->
  <xacro:property name="max_acceleration_steps" value="${254*100}"/> <!-- steps/second² (100% hardware max) -->
  <xacro:property name="max_acceleration_rads" value="${max_acceleration_steps*2*pi/4096}"/> <!-- rad/s² -->

  <!-- Omnidirectional Kinematics Calculations -->
  <!-- For 3-wheel omni drive: ω_i = (-sin(θ_i)·v_x + cos(θ_i)·v_y + R·ω_z) / r -->

  <!-- Maximum allowable linear velocity per axis -->
  <xacro:property name="max_linear_velocity_x" value="${wheel_radius * max_velocity_rads / (sqrt(3)/2)}"/>
  <xacro:property name="max_linear_velocity_y" value="${wheel_radius * max_velocity_rads / 1.0}"/>
  <xacro:property name="max_angular_velocity_z" value="${wheel_radius * max_velocity_rads / wheel_base_offset}"/>

  <!-- Maximum allowable linear acceleration per axis -->
  <xacro:property name="max_linear_acceleration_x" value="${wheel_radius * max_acceleration_rads / (sqrt(3)/2)}"/>
  <xacro:property name="max_linear_acceleration_y" value="${wheel_radius * max_acceleration_rads / 1.0}"/>
  <xacro:property name="max_angular_acceleration_z" value="${wheel_radius * max_acceleration_rads / wheel_base_offset}"/>

  <!-- Motor IDs -->
  <xacro:property name="left_motor_id" value="7"/>
  <xacro:property name="back_motor_id" value="8"/>
  <xacro:property name="right_motor_id" value="9"/>

</robot>
