<?xml version="1.0"?>
<package format="3">
  <name>lekiwi_mujoco</name>
  <version>0.1.0</version>
  <description>MuJoCo models for LeKiwi</description>
  <maintainer email="adityakamath@live.com">Aditya Kamath (Kamath Robotics)</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>lekiwi_description</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
